package com.mythicalgames.ranks;

import eu.okaeri.configs.OkaeriConfig;
import eu.okaeri.configs.annotation.Comment;
import eu.okaeri.configs.annotation.Header;

import java.util.*;

@Header({
    "###############################################",
    "# Mythical Ranks Configuration",
    "# Groups will be saved automatically when you use in-game commands",
    "# DO NOT edit this file while the server is running!",
    "###############################################"
})
public class Config extends OkaeriConfig {
    @Comment(" ")
    @Comment(" ")

    // =========================
    // DATABASE SETTINGS
    // =========================
    @Comment("Database type to use (SQLITE or MONGODB)")
    public DatabaseType database_type = DatabaseType.SQLITE;

    @Comment("MongoDB connection URI (required if database_type is MONGODB)")
    public String mongo_uri = "mongodb://localhost:27017";

    @Comment("MongoDB database name (required if database_type is MONGODB)")
    public String mongo_database_name = "mythical_ranks";

    public enum DatabaseType { SQLITE, MONGODB }

    // =========================
    // RANK SETTINGS
    // =========================
    @Comment("Default group assigned to new players")
    public String defaultGroup = "default";
    @Comment("Shows some additional debug messages :D")
    public boolean debug = true;

    @Comment(" ")
    @Comment(" ")

    @Comment("List of all permission groups (auto-saved by plugin)")
    public Map<String, GroupData> groups = new LinkedHashMap<>();

    public static class GroupData extends OkaeriConfig {

        @Comment("Prefix shown before player name")
        public String prefix = "&7[Member] ";

        @Comment("Nametag format above player's head (use {player} placeholder)")
        public String nametag = "&7{player}";

        @Comment("Chat format for this group ({prefix}, {player}, {message})")
        public String chatFormat = "&7{prefix}{player}: &f{message}";

        @Comment("List of permission nodes")
        public List<String> permissions = new ArrayList<>();

        @Comment("Parent groups this one inherits permissions from")
        public List<String> parents = new ArrayList<>();

        public GroupData() {}

        public GroupData(String prefix, String nametag, String chatFormat, List<String> permissions, List<String> parents) {
            this.prefix = prefix;
            this.nametag = nametag;
            this.chatFormat = chatFormat;
            this.permissions = permissions;
            this.parents = parents;
        }
    }
}
